//
//  Pair.swift
//  CatColours2
//
//  Created by John Sandercock on 11/11/18.
//  Copyright © 2018 Feanor. All rights reserved.
//

import Foundation

/// A pair of genes
///
/// These are accessed by subscripting 1 & 2
struct Pair<T>: CustomStringConvertible where T: Gene {
  var first: T
  var second: T
  
  var expression: T.Trait {
    return first.fuse(other: second)
  }
  
  init(_ first: T, _ second: T? = nil) {
    self.first = first
    self.second = second ?? first
  }
  
  /// - Returns: an array of four pairs of genes that may be generated by this pair and the other pair fusing in germination
  /// - Parameter other: the other pair of genes 'fusing' with this pair of genes
  func allelesPossible(with other: Pair<T>) -> [Pair<T>] {
    return [Pair<T>(other.first, self.first), Pair<T>(other.first, self.second),Pair<T>(other.second, self.first), Pair<T>(other.second, self.second)]
  }
  
  /// - first gene becomes `element`
  /// - if `allowingRecessives` is `true`, only overwrite the second gene if the second gene dominates `element`
  /// - if `allowingRecessives` is `false`, always overwite the second gene as well
  mutating func limit(with element: T, allowingRecessives: Bool) {
    self.first = element
    if allowingRecessives {
      if self.second.dominates(other: element) {
        self.second = element
      }
    } else {
      self.second = element
  }
  }
  /// - first and second genes both become `element`
  mutating func fill(with element: T) {
    self.first = element
    self.second = element
  }
  
  /// ### NOTE: ###
  /// only subscripts allowed are `1` and `2`
  ///
  /// all others cause a fatal error
  subscript(index: Int) -> T {
    get {
      switch index {
      case 1:
        return first
      case 2:
        return second
      default:
        fatalError("Index out of bounds")
      }
    }
    set {
      switch index {
      case 1:
        first = newValue
      case 2:
        second = newValue
      default:
        fatalError("Index out of bounds")
      }
    }
  }
  
  var description: String {
    return "\(first.code)\(second.code)"
  }
}


